- name: Create swap file
  ansible.builtin.command: "dd if=/dev/zero of={{ cif_swap_options.path }} bs=1M count={{ cif_swap_options.size }}"
  args:
    creates: "{{ cif_swap_options.path }}"
  register: cif_swap_creation
- name: Swap file permissions
  ansible.builtin.file:
    path: "{{ cif_swap_options.path }}"
    state: file
    owner: root
    group: root
    mode: 0600
  ignore_errors: "{{ ansible_check_mode }}"
- name: Format swap file
  ansible.builtin.command: "mkswap {{ cif_swap_options.path }}"
  when: cif_swap_creation is changed
- name: Swap conf in fstab
  ansible.builtin.mount:
    src: "{{ cif_swap_options.path }}"
    name: none
    fstype: swap
    opts: sw,nofail
    dump: 0
    passno: 0
    state: present
- name: Activate swap
  ansible.builtin.command: swapon -a
  when: cif_swap_creation is changed
